version: '3'

services:

  frontend:
    image: nginx:1.21.1-alpine
    ports:
      - 8000:80
    volumes:
      - ${PWD}/nginx/html:/usr/share/nginx/html
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api

  api:
    build: ./fastapi/
    command: /start-reload.sh
    environment:
      PORT: 8000
    volumes:
      - ${PWD}/fastapi:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.35
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ${PWD}/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${PWD}/mysql/conf.d/charset.cnf:/etc/mysql/conf.d/charset.cnf

  mlflow:
    build: ./pytorch/
    command: mlflow ui --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ${PWD}/pytorch:/pytorch
    working_dir: /pytorch
