version: '3'

services:
  frontend:
    image: nginx:1.21.1-alpine
    ports:
      - 8000:80
    volumes:
      - ${PWD}/nginx/html:/usr/share/nginx/html
      - ${PWD}/images:/usr/share/nginx/html/images
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api

  api:
    build: ./fastapi/
    command: /start-reload.sh
    environment:
      PORT: 8000
      MYSQL_HOST: db
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - ${PWD}/fastapi:/app
      - ${PWD}/images:/images
    depends_on:
      - db

  db:
    image: mysql:5.7.35
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - ${PWD}/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${PWD}/mysql/conf.d/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ${PWD}/mysql/data:/var/lib/mysql

  mlflow:
    build: ./pytorch/
    command: mlflow ui --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ${PWD}/pytorch:/pytorch
    working_dir: /pytorch
