version: '3'

services:
  pytorch:
    build: .
    command: python3 main.py
    volumes:
      - ${PWD}:/opt/pytorch
    working_dir: /opt/pytorch
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
