version: '3'

services:
  pytorch:
    build: .
    command: python3 main.py
    volumes:
      - ${PWD}:/pytorch
    working_dir: /pytorch
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
